
title: Hung Kim
description: Artificial intelligence , Deep Learning , Machine Learning
show_downloads: false

baseurl: # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://hungk1m.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "anhphtu"
image: 
twitter:
  username: 
#  site:
